name: keepinv
main: keepinv\main
version: 1.0.0
api: 3.15.4
  
author: Honey
description: Oyuncu öldüğünde eşyalarını koruyacak bir plugin

commands:
  keepinv:
    description: "Tek kullanımlık keepinventory özelliği"
    usage: "/keepinv"